# There are two types of categorical variable 
## 1.Ordinal :- Categorical variable in order like:- Good, Best,Better. 
## 2.Nominal :- Categorical variable in non order or not any match like:- State Name 

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("customer.csv")

In [3]:
df.sample(10)

age  gender   review education purchased
43   27    Male     Poor        PG        No
36   34  Female     Good        UG       Yes
42   30  Female     Good        PG       Yes
27   69  Female     Poor        PG        No
4    16  Female  Average        UG        No
2    70  Female     Good        PG        No
29   83  Female  Average        UG       Yes
13   57  Female  Average    School        No
28   48    Male     Poor    School        No
5    31  Female  Average    School       Yes

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
X=df.iloc[:,0:2]

In [7]:
y=df.iloc[:,-1]

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,
                                    random_state=0)

In [10]:
X_train.shape,X_test.shape

((35, 2), (15, 2))

In [11]:
X_train.head()

review education
7      Poor    School
14     Poor        PG
45     Poor        PG
48     Good        UG
29  Average        UG

In [12]:
y_train

7     Yes
14    Yes
45    Yes
48    Yes
29    Yes
15     No
30     No
32    Yes
16    Yes
42    Yes
20    Yes
43     No
8      No
13     No
25     No
5     Yes
17    Yes
40     No
49     No
1      No
12     No
37    Yes
24    Yes
6      No
23     No
36    Yes
21     No
19    Yes
9     Yes
39     No
46     No
3      No
0      No
47    Yes
44     No
Name: purchased, dtype: object

# OrdinalEncoder 
# Encoding the ordinal variable

In [13]:
from sklearn.preprocessing import OrdinalEncoder

In [14]:
oe = OrdinalEncoder([["Poor","Average","Good"],["School","UG","PG"]])

In [15]:
oe.fit(X_train)

X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [16]:
X_train

array([[0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [17]:
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

In [18]:
X_train = pd.DataFrame(X_train,columns=[["review","education"]])
X_test = pd.DataFrame(X_test,columns=[["review","education"]])

In [19]:
X_train.head()

review education
0    0.0       0.0
1    0.0       2.0
2    0.0       2.0
3    2.0       1.0
4    1.0       1.0

In [20]:
X_test.head()

review education
0    0.0       0.0
1    2.0       1.0
2    2.0       1.0
3    2.0       2.0
4    2.0       2.0

# Label Encoding 
## Label encoding always to do with output column.

In [21]:
y_train.shape , y_test.shape

((35,), (15,))

In [22]:
y_train.head()

7     Yes
14    Yes
45    Yes
48    Yes
29    Yes
Name: purchased, dtype: object

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
le  = LabelEncoder()

In [25]:
le.fit(y_train)

LabelEncoder()

In [26]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [27]:
y_train

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [28]:
# 0 is No 1 is Yes
le.classes_

array(['No', 'Yes'], dtype=object)

In [29]:
type(y_train)

numpy.ndarray

# -------------------------------

In [ ]:
y1=pd.DataFrame(y_train)

In [43]:
pd.concat([X_train,y1],axis=1)

(review,)  (education,)  0
0         0.0           0.0  1
1         0.0           2.0  1
2         0.0           2.0  1
3         2.0           1.0  1
4         1.0           1.0  1
5         0.0           1.0  0
6         1.0           1.0  0
7         1.0           1.0  1
8         0.0           1.0  1
9         2.0           2.0  1
10        1.0           0.0  1
11        0.0           2.0  0
12        1.0           1.0  0
13        1.0           0.0  0
14        2.0           0.0  0
15        1.0           0.0  1
16        0.0           1.0  1
17        2.0           0.0  0
18        2.0           1.0  0
19        0.0           1.0  0
20        0.0           0.0  0
21        1.0           2.0  1
22        1.0           2.0  1
23        2.0           0.0  0
24        2.0           0.0  0
25        2.0           1.0  1
26        1.0           2.0  0
27        0.0           2.0  1
28        2.0           1.0  1
29        0.0           2.0  0
30        0.0           2.0  0
31        2.0           2.0  0
32        1.0           0.0  0
33        2.0           2.0  1
34        1.0           1.0  0

# -----------------------------------

In [30]:
y_train = pd.Series(y_train)

In [31]:
type(y_train)

pandas.core.series.Series

In [32]:
y_train

0     1
1     1
2     1
3     1
4     1
5     0
6     0
7     1
8     1
9     1
10    1
11    0
12    0
13    0
14    0
15    1
16    1
17    0
18    0
19    0
20    0
21    1
22    1
23    0
24    0
25    1
26    0
27    1
28    1
29    0
30    0
31    0
32    0
33    1
34    0
dtype: int64

# Train model

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
model = LogisticRegression()

In [35]:
model.fit(X_train,y_train)

LogisticRegression()

In [36]:
ypred = model.predict(X_test)

In [37]:
ypred

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0])

In [38]:
from sklearn.metrics import accuracy_score

In [39]:
accuracy_score(y_test,ypred)

0.5333333333333333