In [1]:
from sklearn.datasets import make_regression

In [15]:
X,y = make_regression(n_samples=100, n_features=2,n_informative=2, n_targets=1,noise=50)

In [16]:
X.shape , y.shape

((100, 2), (100,))

In [25]:
import pandas as pd
df  = pd.DataFrame({"feature1":X[:,0], "feature2":X[:,1] ,"target":y} )

In [26]:
df 

feature1  feature2      target
0  -0.483185 -0.408631   30.671817
1  -0.803239  1.769688  -43.940080
2  -1.054582 -0.029147  -30.303988
3   1.886704 -1.182725  111.175451
4  -1.191000  0.136619   20.233887
..       ...       ...         ...
95  0.056653  0.900898  -12.435683
96 -0.652049 -0.083322   53.384044
97 -0.172093 -1.387051   56.535805
98  0.876517 -0.076227   -4.490330
99  1.595747  0.488949   31.588102

[100 rows x 3 columns]

In [27]:
df.shape

(100, 3)

In [47]:
import plotly.express as px 
import plotly.graph_objects as go
%matplotlib inline

In [48]:
fig = ex.scatter_3d(df,x="feature1",y="feature2",z="target")
fig.show()

In [49]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.show()

In [50]:
import plotly.express as px
import plotly.graph_objects as go

In [51]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.show()

In [52]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

import matplotlib.pyplot as plt 
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
plt.style.use("fivethirtyeight")

In [53]:
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [54]:
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [55]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.show()

In [56]:
np.linspace(-5, 5, 10)

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [59]:
np.random.randint(10,100,10)

array([91, 35, 73, 89, 87, 50, 70, 22, 79, 50])

In [63]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)

In [65]:
np.linspace(-5, 5, 10)

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [ ]:
import numpy as np
from sklearn.datasets import load_diabetes

In [69]:
from sklearn.datasets import load_diabetes

In [76]:
X,y = load_diabetes(return_X_y= True)

In [78]:
X.shape , y.shape

((442, 10), (442,))

In [79]:
from sklearn.model_selection import train_test_split

In [80]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)